[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    links2004/WebSockets@^2.3.4
    bblanchon/ArduinoJson@^6.21.0
    rokit/ESP32Servo@^1.1.0
    robotistan/DabbleESP32@^1.1.0

[env:esp32-wroom]
platform = espressif32
board = esp32-wroom-32
framework = arduino
monitor_speed = 115200
lib_deps = 
    links2004/WebSockets@^2.3.4
    bblanchon/ArduinoJson@^6.21.0
    rokit/ESP32Servo@^1.1.0
    robotistan/DabbleESP32@^1.1.0

[platformio]
default_envs = esp32-wroom